teamterning/Terning-Android

- core/src/main/java/com/terning/core/designsystem/textfield/TerningBasicTextField.kt
- feature/src/main/java/com/terning/feature/main/MainNavigator.kt
- closed #23 
- 포커스 여부에 따라 힌트 텍스트 색상 변경
https://github.com/teamterning/Terning-Android/assets/97820109/abd8f442-3fdc-4c19-a9d6-95a7f437b265
- 영상에서 두 텍스트 필드에 동시에 입력되는데 이거는 임의로 넣은 코드라.. 신경 안쓰셔도 됩니닷
> [FEAT/#23] 포커스 여부에 따라 힌트 텍스트 색상 변경

- core/src/main/java/com/terning/core/designsystem/component/textfield/NameTextField.kt
- core/src/main/java/com/terning/core/designsystem/component/textfield/SearchTextField.kt
- core/src/main/java/com/terning/core/designsystem/component/textfield/TerningBasicTextField.kt
- core/src/main/java/com/terning/core/designsystem/textfield/SearchTextField.kt
- feature/src/main/java/com/terning/feature/search/SearchRoute.kt
> [FIX/#25] develop 브렌치 / 주석 및 컴포넌트 수정

- core/src/main/java/com/terning/core/designsystem/component/topappbar/TerningBasicTopAppBar.kt
- core/src/main/java/com/terning/core/designsystem/theme/Color.kt
- core/src/main/java/com/terning/core/designsystem/theme/Theme.kt
> [ADD/#35] Color 속성 추가

- core/src/main/java/com/terning/core/designsystem/component/box/ScrapBox.kt
- closed #38 
- 홈화면과 캘린더 스크랩 화면에서 공통적으로 사용되는 박스 컴포넌트 구현
홈 화면과 캘린더 화면에서 사용되는 스크랩 박스 컴포넌트입니다.
- `modifier`를 통해 박스의 크기를 지정 합니다.
- `content`로 박스 우측에 들어갈 컴포저블을 지정합니다.
- `borderWidth`와 `elevation`을 사용하여 박스의 테두리와 그림자 효과를 부여합니다.
홈화면에서 사용되는지 캘린더 화면에서 사용되는지를 구분하지 않았기 때문에, 사용하실 때 직접 modifier를 통해 뷰의 크기 지정을 해줘야 합니다!!
> [ADD/#38] ScrapBox 컴포넌트 구현

- core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SortBy.kt
- core/src/main/java/com/terning/core/designsystem/component/bottomsheet/SortingBottomSheet.kt
- core/src/main/java/com/terning/core/designsystem/component/bottomsheet/TerningBasicBottomSheet.kt
- core/src/main/java/com/terning/core/designsystem/component/button/SortingButton.kt
- core/src/main/res/drawable/ic_down.xml
- core/src/main/res/values/strings.xml
- feature/src/main/java/com/terning/feature/onboarding/signup/component/SignUpBottomSheet.kt
- closed #32
- SortingButton 구현
- SortingBottomSheet 구현
https://github.com/teamterning/Terning-Android/assets/98209004/eb7aab14-7610-4e26-a858-48fbabda4142
- 사용 방법은 노션 참고해주세요😎
> [ADD/#32] 공고 정렬 바텀시트 구현

- core/src/main/java/com/terning/core/designsystem/component/item/InternItem.kt
- core/src/main/java/com/terning/core/designsystem/component/item/ScrapBox.kt
- feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrap.kt
- closed #62 
- 인턴 공고 컴포넌트 로직 수정
로직 수정이라 스샷은 없습니다!
- 컴포넌트의 크기 설정 방식을 조금 수정하였습니다!!
내부 컴포넌트 크기를 토대로 외부 레이아웃의 크기가 정해지도록 구현했습니다.
- 스크랩 색상이 붙은 박스 로직도 조금 수정되었습니다!!
> [FIX/#62] 인턴 공고 컴포넌트

- app/build.gradle.kts
- app/src/main/java/com/terning/point/di/AuthInterceptor.kt
- app/src/main/java/com/terning/point/di/DataSourceModule.kt
- app/src/main/java/com/terning/point/di/RepositoryModule.kt
- app/src/main/java/com/terning/point/di/RetrofitModule.kt
- app/src/main/java/com/terning/point/di/ServiceModule.kt
- app/src/main/java/com/terning/point/di/qualifier/RetrofitQualifier.kt
- core/src/main/java/com/terning/core/extension/ContextExt.kt
- data/src/main/java/com/terning/data/datasource/TokenReissueDataSource.kt
- data/src/main/java/com/terning/data/datasourceimpl/TokenReissueDataSourceImpl.kt
- data/src/main/java/com/terning/data/dto/response/TokenReissueResponseDto.kt
- data/src/main/java/com/terning/data/repositoryimpl/TokenReissueRepositoryImpl.kt
- data/src/main/java/com/terning/data/service/TokenReissueService.kt
- domain/src/main/java/com/terning/domain/entity/response/TokenReissueResponseModel.kt
- domain/src/main/java/com/terning/domain/repository/TokenReissueRepository.kt
- gradle/libs.versions.toml
> [FEAT/#96] 토큰 재발급 / 서버통신 구현

- data/src/main/java/com/terning/data/dto/response/InternResponseDto.kt
- domain/src/main/java/com/terning/domain/entity/response/InternInfoModel.kt
- feature/src/main/java/com/terning/feature/intern/InternRoute.kt
- feature/src/main/java/com/terning/feature/intern/InternViewState.kt
- feature/src/main/java/com/terning/feature/intern/component/InternBottomBar.kt
- feature/src/main/java/com/terning/feature/intern/component/ScrapCancelDialog.kt
- closed #117 
- 공고 모델 수정
https://github.com/user-attachments/assets/d587da1b-d399-459b-a12f-02019e015ecb
-
> [HOTFIX/#117] 공고 뷰 / 공고 상세 페이지 API 수정

- core/src/main/java/com/terning/core/designsystem/component/item/InternItemWithShadow.kt
- core/src/main/res/values/strings.xml
- data/src/main/java/com/terning/data/dto/response/HomeRecommendInternResponseDto.kt
- domain/src/main/java/com/terning/domain/entity/response/HomeRecommendInternModel.kt
- feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
- feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
- feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
- feature/src/main/java/com/terning/feature/home/home/component/HomeTodayIntern.kt
- feature/src/main/java/com/terning/feature/home/home/component/HomeTodayInternDialog.kt
- feature/src/main/java/com/terning/feature/home/home/model/HomeDialogState.kt
- closed #146 
- 오늘 마감 공고 다이얼로그
- 딱 맞는 인턴 공고 다이얼로그
- 스크랩 관련 서버 통신 
https://github.com/user-attachments/assets/88c2526a-f7c8-479d-8580-0272f59ee99c
- 드디어!!!!!! 다이얼로그 성공!!!!!!
- 근데 통신하고 나서 결과 반영하는게 조금 이상하네요🥹 QA 반영하면서 같이 고쳐보겠습니다!!
> [UI#146] 홈 뷰 / 다이얼로그 구현

- feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
- feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
- closed #171 
- 탐색뷰 리스트 화면에서 스크랩 시 색상이 적용되지 않는 오류 수정
> [FIX/#171] 스크랩 오류 수정

- .github/workflows/dokka.yml
- app/build.gradle.kts
- build.gradle.kts
- core/build.gradle.kts
- core/docs.md
- core/src/main/java/com/terning/core/designsystem/component/button/TerningBasicButton.kt
- gradle/libs.versions.toml
- closed #175
- 자동 배포 테스트 완료했습니다!!!
- 이 피알 develop에 머지하면 이제부터 `gh-pages` 브렌치에 문서가 자동으로 배포될 거에요!
- 작성 예시는 `TerningBasicButton.kt`에 작성해뒀으니까 참고하면 됩니다.
- `KDoc` 언어로 작성하면 돼요.
> /** 로 시작하여 */로 끝납니다.
> 컴포넌트에 대한 설명을 작성해주면 됩니다.
>모든 블록태그는 줄의 앞부분에 위치하고 @로 시작해요.
> [FEAT/#175] 컴포넌트 문서화

- feature/src/main/java/com/terning/feature/intern/component/InternTitle.kt
- feature/src/main/java/com/terning/feature/search/search/component/ImageSlider.kt
- feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
- closed #275 
- 배너 수정
- 지원마감 색상 변경
- 검색결과 없을시 화면 적용
https://github.com/user-attachments/assets/8670d223-1485-4f50-bdd2-ed898425d78c
- 터닝 배포 최고당...! 최종 큐에이 감격이네욥.
> [FIX/#275] 탐색 뷰 최종 QA

- feature/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
- closed #296 
- `coerceAtMost`로 달력 전환 시 선택된 날짜이 현재 달의 최대 날짜보다 큰 경우, 현재 달의 최대 날짜로 조절하도록 수정
- 현재 달의 최대 날짜는 `LocalDate.month.minLength`로 불러옴
- 문제 상황
https://github.com/user-attachments/assets/840db89a-b995-4811-9cd3-5bd9eee6812a
- 문제 해결
https://github.com/user-attachments/assets/ca88647b-fa8b-43c7-918b-2cd315a76f9a
- PlayConsole 구경하다가 에러 터졌다고 해서 급하게 수정했어요,,,
- 후딱 머지하고 31일 되기 전에 업데이트합시당ㅋㅎㅋ
> [FIX/#296] DateTimeException 해결

- feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
- feature/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringRoute.kt
- feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
- gradle/libs.versions.toml
- closed #300
- 이슈 300번째와 함께 3차 스프린트 시작~
> [FEAT/#300] 엠플리튜드 이벤트 심기

- build-logic/src/main/java/terning.android.feature.gradle.kts
- core/designsystem/docs.md
- core/designsystem/src/main/java/com/terning/core/designsystem/component/button/RectangleButton.kt
- core/designsystem/src/main/java/com/terning/core/designsystem/component/button/RoundButton.kt
- core/designsystem/src/main/java/com/terning/core/designsystem/component/button/TerningBasicButton.kt
- feature/filtering/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringRoute.kt
- feature/filtering/src/main/java/com/terning/feature/filtering/startfiltering/navigation/StartFilteringNavigation.kt
- feature/filtering/src/main/java/com/terning/feature/filtering/starthome/StartHomeRoute.kt
- feature/filtering/src/main/res/values/strings.xml
- feature/main/src/main/java/com/terning/feature/main/MainScreen.kt
- gradle/libs.versions.toml
- closed #304
https://github.com/user-attachments/assets/abc66c20-5ba1-406b-a9ba-9fcdecb56285
https://github.com/user-attachments/assets/36995f63-c7d8-4c76-b74b-1b4ca7f14cdd
- 컴포즈 며칠 안 했다고 낯가려서 다시 친해지는 중입니다..
> [FEAT/#304] 온보딩 뷰 / 필터링 건너뛰기 추가

- feature/home/src/main/java/com/terning/feature/home/component/HomeYearMonthPicker.kt
- feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/PlanFilteringScreen.kt
- closed #319
- 처음 체크박스 선택 시에도 저장버튼은 활성화 됨
- 저장한 값 그대로 뜸
- 년, 월 중 하나라도 null일 경우 저장 버튼은 비활성화됨
https://github.com/user-attachments/assets/f146d7b7-2044-4416-b9e8-0fe2598f6c39
- 사실 코드가 크게 바뀐 건 없구 기존 오류 사항들은 많이 잡혔어요
- 효빈언니 브렌치로 머지하도록 되어있어서 꼭 제 피알 머지하구 313번 브렌치 머지해주세용...!!!!!!
- 추가로 체크박스 활성여부 작성하는 줄에 `||`가 빠져있어서 이것만 추가했어요..! 혹시 이 부분 효빈언니 브렌치에 이미 반영되있다면 지우도록 할게요!
> [FIX/#319] 필터링 재설정 뷰 / 데이트피커 로직 수정 

- core/designsystem/src/main/res/values/strings.xml
- feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/HomeFilteringBottomSheet.kt
- feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/PlanFilteringScreen.kt
- closed #323
- 홈, 검색 뷰 정렬 버튼 라이팅 수정
- 필터링 재설정 뷰 진입 시 계획 필터링 null일 경우 체크박스 체크
- 체크박스 해제 시 저장하기 버튼 비활성화
- 페이지 이동 시 선택한 필터링 정보 유지
https://github.com/user-attachments/assets/5af0bf0a-f292-4c99-9b5a-48e4ce5114ce
- 짜잔~~ QA 다 반영했습니다!!
- 혹시 잘못 적용된 부분들 있으면 말씀해주세요..!!
> [FIX/#323] 홈, 필터링 재설정 뷰 / 1차 QA 반영

- core/designsystem/src/main/java/com/terning/core/designsystem/util/CalendarDefaults.kt
- feature/filtering/src/main/java/com/terning/feature/filtering/startfiltering/StartFilteringRoute.kt
- feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/HomeYearMonthPicker.kt
- feature/home/src/main/java/com/terning/feature/home/component/bottomsheet/PlanFilteringScreen.kt
- feature/mypage/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
- closed #322
| 온보딩 | 데이트피커 |
|:----------:|:------------:|
| <img src="https://github.com/user-attachments/assets/8bb9a949-3132-4f97-a1f7-cb92ed18bfa0" width=300 /> | <video src="https://github.com/user-attachments/assets/7e211fff-0845-4381-9966-a32f09909322" width=270 /> |
- 3차 스프린트 1차 큐에이 완료!!
> [FIX/#322] 온보딩, 데이트피커 / 3차 스프린트 QA 반영

- feature/calendar/src/main/java/com/terning/feature/calendar/calendar/component/group/CalendarWeekGroup.kt
- closed #330 
- 월간 달력 터치 영역 수정
https://github.com/user-attachments/assets/94c750a3-89fd-4a48-8229-b6db1edc4c8f
- 2025년 1월 13일, 2024-25 잉글랜드 FA컵 3라운드 맨체스터 유나이티드 vs 아스널 경기를 시청하던 중 터닝 디자이너님께서 올려주신 QA를 빠르게 해결한 PR입니다.
- 맨체스터 유나이티드의 승리를 기원합니다.
> [FIX/#330] 달력 영역 수정

- data/search/build.gradle.kts
- data/search/src/main/java/com/terning/data/search/datasourceimpl/SearchDataSourceImpl.kt
- data/search/src/main/java/com/terning/data/search/dto/request/SearchRequestDto.kt
- data/search/src/main/java/com/terning/data/search/mapper/SearchResultMapper.kt
- data/search/src/main/java/com/terning/data/search/pagingsource/SearchPagingSource.kt
- data/search/src/main/java/com/terning/data/search/repositoryimpl/SearchRepositoryImpl.kt
- domain/search/build.gradle.kts
- domain/search/src/main/java/com/terning/domain/search/entity/SearchResult.kt
- domain/search/src/main/java/com/terning/domain/search/repository/SearchRepository.kt
- feature/search/build.gradle.kts
- feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
- feature/search/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
- feature/search/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
- gradle/libs.versions.toml
- closed #328 
- 탐색 뷰 페이징 추가
https://github.com/user-attachments/assets/f769a273-d95a-4d9d-b7ec-c59da52c95e9
- 너무 어려워서 하루죙일 붙잡고 있는데 로직이 맞는 건지,.,..,
> [FEAT/#328] 탐색 뷰 / 페이징 추가

- .gitignore
- app/build.gradle.kts
- build-logic/build.gradle.kts
- build-logic/src/main/java/com/terning/build_logic/convention/ComposeAndroid.kt
- build.gradle.kts
- gradle/libs.versions.toml
- closed #346
- 터닝도 드디어 코틀린 2.0 적용..!!🥹
> [FEAT/#346] Kotlin 2.0 마이그레이션

- core/designsystem/src/main/java/com/terning/core/designsystem/type/NotificationRedirect.kt
- core/designsystem/src/main/java/com/terning/core/designsystem/util/DeeplinkDefaults.kt
- core/firebase/build.gradle.kts
- core/firebase/src/main/java/com/terning/core/firebase/messageservice/TerningMessagingService.kt
- feature/calendar/src/main/java/com/terning/feature/calendar/calendar/CalendarRoute.kt
- feature/calendar/src/main/java/com/terning/feature/calendar/calendar/navigation/CalendarNavigation.kt
- feature/home/src/main/java/com/terning/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/terning/feature/home/navigation/HometNavigation.kt
- feature/main/build.gradle.kts
- feature/main/src/main/java/com/terning/feature/main/MainActivity.kt
- feature/main/src/main/java/com/terning/feature/main/MainNavigator.kt
- feature/main/src/main/java/com/terning/feature/main/MainScreen.kt
- feature/mypage/src/main/java/com/terning/feature/mypage/mypage/MyPageRoute.kt
- feature/mypage/src/main/java/com/terning/feature/mypage/profileedit/ProfileEditRoute.kt
- feature/search/src/main/java/com/terning/feature/search/search/SearchRoute.kt
- feature/search/src/main/java/com/terning/feature/search/search/navigation/SearchNavigation.kt
- feature/splash/src/main/java/com/terning/feature/splash/SplashRoute.kt
- feature/splash/src/main/java/com/terning/feature/splash/navigation/SplashNavigation.kt
- closed #382
| LargeIcon 적용 사진 | 
|:------:|
| <image src="https://github.com/user-attachments/assets/bcbbb15a-1dc2-4a49-933e-6e3e2b48e709" width = 500/>| 
| 처음 알림 클릭 시 <br> `(탐색으로 가는 알림)` | 포그라운드 상태에서 알림 클릭 시 <br> `(홈으로 가는 알림)` | 
|:------:|:-------:|
| <video src="https://github.com/user-attachments/assets/51571290-4cb2-4d4f-aae4-bf935e3d003b"></video> | <video src="https://github.com/user-attachments/assets/60435f28-169c-4557-a862-bb234bfe09b3"></video>  | 
- 드디어 길고 길었던 푸시알림 구현이 끝났습니다!🥹
- 알림을 클릭했을 때 무조건 스플래쉬를 거치는 것은 맞지만, 앱이 활성화 되어있는 상태(포그라운드)일 때는 바로 그 화면으로 이동하도록 했어요!
- 이를 구현하면서 앱의 진입점(`startDestination`)을 매번 바꾸는 방향으로 수정했습니다! (아린언니 보고 참고해주세요!)
- 고려하지 않게 된 두 가지 사항에 대해서도 이유를 작성해보겠습니당
1. `업데이트 확인하기(포그라운드)` : 알림 자체를 처음 눌렀을 때는 스플래쉬를 거치기 때문에, 굳이 사용자가 앱을 쓰고 있을 때 업데이트가 일어나는 경우는 고려할 필요가 없다고 판단. …
> [FEAT/#382] FCM 푸시알림 커스텀 / Payload 형식에 맞게 구현

- core/analytics/src/main/java/com/terning/core/analytics/EventType.kt
- core/firebase/build.gradle.kts
- core/firebase/src/main/java/com/terning/core/firebase/messageservice/TerningMessagingService.kt
- feature/main/src/main/java/com/terning/feature/main/MainActivity.kt
- closed #384
- 알림으로 연 딥링크라는 것을 식별하기 위해 `FROM_NOTIFICATION`을 추가해줬습니다! 카카오톡으로 딥링크 열면 이벤트 안 심어질 거에요!
- 포그라운드 상태에서 알림을 클릭하면 이벤트가 두 번 축적되는 문제가 있어서 `ALREADY_TRACKED`로 구분해줬어요..!
> [ADD/#384] 4차 스프린트 / 엠플리튜드 이벤트 추가

- data/home/src/main/java/com/terning/data/home/datasource/HomeDataSource.kt
- data/home/src/main/java/com/terning/data/home/datasourceimpl/HomeDataSourceImpl.kt
- data/home/src/main/java/com/terning/data/home/dto/request/FcmTokenRequestDto.kt
- data/home/src/main/java/com/terning/data/home/mapper/FcmTokenMapper.kt
- data/home/src/main/java/com/terning/data/home/repositoryimpl/HomeRepositoryImpl.kt
- data/home/src/main/java/com/terning/data/home/service/HomeService.kt
- domain/home/src/main/java/com/terning/domain/home/entity/FcmToken.kt
- domain/home/src/main/java/com/terning/domain/home/repository/HomeRepository.kt
- feature/home/src/main/java/com/terning/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/terning/feature/home/HomeViewModel.kt
- closed #390
- 해당 API를 연결하는 다이얼로그입니다!
- 현재 기존 유저는 FCM 토큰을 발급할 수 있는 로직이 없어서 알림 다이얼로그를 띄울 때 FCM 토큰을 서버에 보내는 로직을 추가해 줬습니다.
- 서버 팀원에 문의해 보았을 때 이 API는 "`해당 유저가 이미 존재하고 토큰값이 일치하지 않다면 변경해주고, 존재하지않으면 새롭게 반영해주는 로직`" 이라고 합니다.
- 이 때문에 알림 다이얼로그가 다시 떠서 해당 API가 재호출되더라도 성능상 큰 차이가 없어 문제 없을 거라는 답변을 받았습니다..!
- 추가로.. 아키텍처적인 고민도 있었는데 home 뷰라서 `:domain:home` 모듈에 작성하긴 했는데 회원을 관리하는 도메인에 넣을까 하다가 이는 리팩토링 할 때 한 번에 하는 게 좋을 것 같아 일단은 이렇게 구현했습니당..!
> [FEAT/#390] 일회성 FCM 토큰 / 서버통신 구현
