- feature/src/main/java/com/terning/feature/calendar/scrap/CalendarScrapListScreen.kt
- closed #66 
- 월에 포함되지 않는 날이 인덱스에 포함되어 오류가 발생해 수정하게 되었습니다!
> [HOTFIX/#66] 인덱싱 오류 수정

- app/src/main/AndroidManifest.xml
- feature/src/main/AndroidManifest.xml
> [FIX/#82] Manifest 수정

- feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
- feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
- feature/src/main/java/com/terning/feature/onboarding/signup/SignUpRoute.kt
- feature/src/main/java/com/terning/feature/onboarding/signup/SignUpViewModel.kt
- feature/src/main/java/com/terning/feature/onboarding/signup/navigation/SignUpNavigation.kt
- closed #111
- 이제 온보딩 문제 없습니당!
> [FIX/#109] 온보딩 / 서버통신 수정

- app/src/main/java/com/terning/point/di/DataSourceModule.kt
- app/src/main/java/com/terning/point/di/RepositoryModule.kt
- app/src/main/java/com/terning/point/di/ServiceModule.kt
- core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageLogoutBottomSheet.kt
- core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
- data/src/main/java/com/terning/data/datasource/MyPageDataSource.kt
- data/src/main/java/com/terning/data/datasourceimpl/MyPageDataSourceImpl.kt
- data/src/main/java/com/terning/data/repositoryimpl/MyPageRepositoryImpl.kt
- data/src/main/java/com/terning/data/service/MyPageService.kt
- domain/src/main/java/com/terning/domain/repository/MyPageRepository.kt
- feature/build.gradle.kts
- feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
- feature/src/main/java/com/terning/feature/mypage/MyPageState.kt
- feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
- closed #106
https://github.com/user-attachments/assets/bd4c31d7-22e2-4560-9f26-55b56a83038f
- 로그아웃도 완료~!
> [FEAT/#106] 로그아웃 / 서버통신 구현

- core/src/main/java/com/terning/core/designsystem/component/bottomsheet/MyPageQuitBottomSheet.kt
- data/src/main/java/com/terning/data/datasource/MyPageDataSource.kt
- data/src/main/java/com/terning/data/datasourceimpl/MyPageDataSourceImpl.kt
- data/src/main/java/com/terning/data/repositoryimpl/MyPageRepositoryImpl.kt
- data/src/main/java/com/terning/data/service/MyPageService.kt
- domain/src/main/java/com/terning/domain/repository/MyPageRepository.kt
- feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
- feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
- closed #116
https://github.com/user-attachments/assets/82e34f2c-4ce5-4089-b833-3050336326f0
- 탈퇴 잘 되는 거 확인 완료 !
> [FEAT/#116] 계정탈퇴 / 서버통신 구현

- data/src/main/java/com/terning/data/datasource/MyPageDataSource.kt
- data/src/main/java/com/terning/data/datasourceimpl/MyPageDataSourceImpl.kt
- data/src/main/java/com/terning/data/dto/response/MyPageResponseDto.kt
- data/src/main/java/com/terning/data/repositoryimpl/MyPageRepositoryImpl.kt
- data/src/main/java/com/terning/data/service/MyPageService.kt
- domain/src/main/java/com/terning/domain/entity/response/MyPageProfileModel.kt
- domain/src/main/java/com/terning/domain/repository/MyPageRepository.kt
- feature/src/main/java/com/terning/feature/mypage/MyPageRoute.kt
- feature/src/main/java/com/terning/feature/mypage/MyPageState.kt
- feature/src/main/java/com/terning/feature/mypage/MyPageViewModel.kt
- feature/src/main/java/com/terning/feature/onboarding/signin/SignInViewModel.kt
- closed #119
- 서버 전부 붙이기 완료 ㅎㅎ
> [FEAT/#119] 마이페이지 정보 서버통신 구현

- app/src/main/java/com/terning/point/di/AuthInterceptor.kt
- core/src/main/java/com/terning/core/designsystem/component/item/InternItemWithShadow.kt
- data/src/main/java/com/terning/data/datasource/SearchDataSource.kt
- data/src/main/java/com/terning/data/datasourceimpl/SearchDataSourceImpl.kt
- data/src/main/java/com/terning/data/dto/request/SearchRequestDto.kt
- data/src/main/java/com/terning/data/dto/response/SearchResultResponseDto.kt
- data/src/main/java/com/terning/data/dto/response/SearchScrapsResponseDto.kt
- data/src/main/java/com/terning/data/dto/response/SearchViewsResponseDto.kt
- data/src/main/java/com/terning/data/repositoryimpl/SearchRepositoryImpl.kt
- data/src/main/java/com/terning/data/service/SearchService.kt
- domain/src/main/java/com/terning/domain/entity/response/InternshipAnnouncementModel.kt
- domain/src/main/java/com/terning/domain/entity/response/SearchResultModel.kt
- domain/src/main/java/com/terning/domain/repository/SearchRepository.kt
- feature/src/main/java/com/terning/feature/search/search/SearchRoute.kt
- feature/src/main/java/com/terning/feature/search/search/SearchViewsState.kt
- feature/src/main/java/com/terning/feature/search/search/component/SearchInternList.kt
- feature/src/main/java/com/terning/feature/search/search/model/SearchScrapsListState.kt
- feature/src/main/java/com/terning/feature/search/search/model/SearchViewsListState.kt
- feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessRoute.kt
- feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessSideEffect.kt
- feature/src/main/java/com/terning/feature/search/searchprocess/SearchProcessViewModel.kt
- feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchProcessState.kt
- feature/src/main/java/com/terning/feature/search/searchprocess/models/SearchResultState.kt
- closed #110 
- 검색 결과 요청
- 검색 결과에 따라 화면 매핑
https://github.com/user-attachments/assets/b93f988a-ee19-4c4b-9901-d8a69e19e8f8
-
> [FEAT/#110] 탐색 뷰 / 검색 결과 화면 API 연동

- feature/src/main/java/com/terning/feature/home/changefilter/ChangeFilterRoute.kt
- feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
- feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
- closed #122
- 공고 정렬 기준 변경
- 유저 이름 출력
https://github.com/user-attachments/assets/4f05e15b-6ff9-499d-a9a2-aa71706d0e34
- 짜잔~
> [FEAT/#122] 홈 뷰 / 공고 정렬 기준 변경 구현

- feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
- feature/src/main/java/com/terning/feature/home/home/HomeViewModel.kt
- closed #139
- 홈 뷰 초기 필터링 오류 해결
- 홈뷰,,,, 화이팅,,,,,
> [HOTFIX/#139] 초기 필터링 오류 해결

- feature/src/main/java/com/terning/feature/onboarding/signin/SignInRoute.kt
> [HOTFIX/#148] 스플래시 배경 추가

- feature/src/main/java/com/terning/feature/home/home/HomeRoute.kt
- feature/src/main/java/com/terning/feature/home/home/component/HomeRecommendInternDialog.kt
- closed #154
- 필터링 정보 업데이트
- 드디어 QA 반영 끄읏~
> [FIX/#154] 홈 뷰 1차 QA 반영

- feature/src/main/java/com/terning/feature/onboarding/splash/SplashScreen.kt
- closed #161
- 홈화면에서 뒤로가기 버튼 클릭 시 종료됩니다.
- 다른 화면으로 이동하게 되면 스택에 쌓이게 됩니다.
> [FIX/#161] Home 화면에서 종료 구현

- feature/src/main/java/com/terning/feature/intern/component/ScrapDialogContent.kt
- closed #issue number
- task1
- task2
- task3
-
> [FIX] 색상 변경

- feature/src/main/java/com/terning/feature/home/home/component/HomeFilteringEmptyIntern.kt
> [FIX/#173] 홈 뷰 / 텍스트 스타일 지정

- app/build.gradle.kts
- closed #196
- 테스트 서버 주소 나오면 그것도 바로 추가할게요!
> [ADD/#196] 릴리즈 서버 추가

- app/build.gradle.kts
- core/build.gradle.kts
- feature/build.gradle.kts
- gradle/libs.versions.toml
- closed #198
- 컴포즈 프리뷰가 디버그 모드로 되어 있어서 릴리즈 모드에서는 돌아가지 않아, 수정했습니다!
- 고치는 김에 안 쓰는 라이브러리도 정리해주었어요
> [FIX/#198] 릴리즈 모드 수정

- .github/workflows/dokka.yml
- .github/workflows/pr_checker.yml
- closed #216
- 테스트 서버 추가함에 따라 배포 파일도 바꿔줘야 하는 걸 깜빡했네요 ㅎ..
- 하는 김에 피알 체커도 수정해주었습니다
> [FIX/#216] 테스트 서버 / 접근 권한 추가

- feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
- feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialogViewModel.kt
- feature/src/main/java/com/terning/feature/dialog/detail/component/ColorPalette.kt
- feature/src/main/java/com/terning/feature/dialog/detail/component/ScrapColorChangeButton.kt
- feature/src/main/java/com/terning/feature/dialog/detail/component/ScrapInfoRow.kt
- feature/src/main/java/com/terning/feature/dialog/detail/state/ScrapDialogUiState.kt
- closed #244 
- 다이얼로그 버튼 로직 변경
- 기존: 바뀐 색상을 저장하면 "변경 완료" 표시가 됨
- 변경: 색상을 바꾸면 다이얼로그가 꺼짐
https://github.com/user-attachments/assets/e3b4abd9-2bd4-405d-ab6b-deac0655d34a
- 색상을 수정하는 경우 다이얼로그 처리 방식이 달라졌습니다~
- QA가 없어서 코드 리팩이나 더 할 예정입니다! 혹시 뭐 문제있으면 바로 알려주세여~
> [MOD/#244] 다이얼로그 버튼 수정

- data/src/main/java/com/terning/data/datasourceimpl/AuthDataSourceImpl.kt
- data/src/main/java/com/terning/data/service/AuthService.kt
> [FIX/#255] 회원가입 / 서버통신 수정 

- data/src/main/java/com/terning/data/dto/response/HomeRecommendInternResponseDto.kt
- closed #257
- 맞춤 공고 api response 네이밍 수정
UI는 바뀐 것 없습니다!
- response 중 internshipAnnouncementId 이름만 수정되었습니다!
> [FIX/#257] 홈 뷰 / 맞춤 공고 api 수정사항 반영

- .github/workflows/dokka.yml
- .github/workflows/pr_checker.yml
> [FIX/#271] CI/CD 수정

- feature/src/main/java/com/terning/feature/dialog/detail/ScrapDialog.kt
- feature/src/main/res/values/strings.xml
- closed #273  
- 스크랩 수정 시 토스트 메시지 추가
https://github.com/user-attachments/assets/6f5e7e88-abaa-4cea-85e5-06453ec417f9
- 최종 QA 반영했습니다~
- 문득 드는 생각인데 혹시 다른 분들은 각각의 화면에서 스크랩 수정 시 토스트 메시지가 나오도록 하셨나요??
> [FIX/#273] 다이얼로그 QA 반영

- feature/src/main/java/com/terning/feature/intern/component/InternCompanyInfo.kt
- gradle/libs.versions.toml
- closed #283
- 1.1.4 업데이트 준비 할 완료
> [FIX/#283] 릴리즈 마지막 작업

- gradle/libs.versions.toml
- closed #291
- 오늘의 메모: 커밋을 까먹지 말자  
- 버전 올라갑니당
> [MOD/#291] 버전 업데이트 1.1.4 -> 1.1.5

- gradle/libs.versions.toml
- closed #334
- versionCode 수정 (10200 -> 102000)
- 10200 < 102000 ....
- `오류 사유`: 버전 숫자를 이전보다 낮게 적어서
- `교훈`: 산수를 잘하겠습니다.
> [CHORE/#334] 버전 업그레이드

- feature/main/src/main/AndroidManifest.xml
- gradle/libs.versions.toml
- closed #336
- **문제 상황**: 토큰 만료 시 `ProcessPhoenix`를 이용하여 앱을 재시작 하는데 `DEFAULT category`가 없어 IllegalStateException을 발생시키고 있었습니다.
- **해결 방안**: MainActivity의 메니페스트에 `DEFAULT category`를 추가하였습니다.
- **참고 링크**: https://code.luasoftware.com/tutorials/android/how-to-restart-android-app-programmatically
> [FIX/#336] 토큰 만료 시 IllegalStateException 해결

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- build.gradle.kts
- gradle/libs.versions.toml
- closed #348
| 디버그 | 릴리즈 |
| --- | --- |
| ![Screenshot_20250306_000955_One UI Home](https://github.com/user-attachments/assets/58930643-ed0a-4996-ab5d-2f58cf9ac91b) | ![Screenshot_20250306_001103_One UI Home](https://github.com/user-attachments/assets/46920796-9cbd-438c-b113-9744c31410a5) |
- 다른 사람들도 이어서 작업해야 해서 파이어베이스 연동만 해뒀어요.
- 알림 권한 관련해서는 마이페이지 작업하면서 해둘게요!
> [FEAT/#348] Firebase 연동

- core/firebase/build.gradle.kts
- gradle/libs.versions.toml
- closed #394
- versionCode 오류는 눈감아줘요...😅
- 마지막으로.. 사랑하는 안두 오빠언니덜,,,4차 스프린트까지 너무너무 수고했어요💚
> [CHORE/#394] 버전 업데이트 1.3.0 -> 1.3.4

- gradle/libs.versions.toml
> [CHORE/#397] 버전 업데이트 1.3.4 -> 1.3.5
